name: HTML File Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start web server
        run: |
          python3 -m http.server 8000 &
          sleep 5 # Wait for the server to start

      - name: Access HTML file
        run: |
          curl -O http://localhost:8000/cryptoanalysis.html
          cat cryptoanalysis.html
